
# Go generate the sha-hash run
# HASH=$(openssl sha256  das2C-${VERSION}.tar.gz | awk '{print $2}')
#
# Example:
#  openssl sha256 das2C-2.3-pre3.tar.gz | awk '{print $2}'

{% set name = "das2c" %}
{% set conda_version = "2.3.0" %}
{% set git_version = "2.3.0" %}
{% set sha256 = "92d3472766d683f164b6df4b2955a4c15a3170f7f751462c4937eab1fae1f0dd" %}

package:
   name: {{ name }} 
   version: {{ conda_version }} 
   
source:
   fn:  das2C-{{ git_version }}.tar.gz
   url: https://github.com/das-developers/das2C/archive/refs/tags/v{{ git_version }}.tar.gz
   sha256: {{ sha256 }}
   
   
build:
   # This is the zeroth build
   number: 0
   
requirements:
   build:
      - {{ compiler('c') }}
            
   host:
      - expat
      - fftw
      - zlib
      - openssl
      - pthreads4w [win]
      
   run:
      - expat
      - fftw
      - zlib
      - openssl
      - pthreads4w [win]
      
test:
   

about:
   home: https://github.com/das-developers/das2C
   license: LGPL-2.1
   license_file: LICENSE
   summary: das2 stream utilities and catalog client in C
