
# Go generate the sha-hash run
# HASH=$(openssl sha256  das2C-${VERSION}.tar.gz | awk '{print $2}')
#
# Example:
#  openssl sha256 das2C-tmp.tar.gz | awk '{print $2}'

{% set name = "das2c" %}
{% set conda_version = "3.0.2" %}
{% set git_version = "3.0-pre2" %}
{% set sha256 = "28fd7b8dc77fb537ed437b67c5464ffaaff3c3e77dcf7ca4cdcb5cec7e96a11f" %}

package:
   name: {{ name }} 
   version: {{ conda_version }} 
   
source:
   fn:  das2C-{{ git_version }}.tar.gz
   #url: https://github.com/das-developers/das2C/archive/refs/tags/v{{ git_version }}.tar.gz
   url: https://space.physics.uiowa.edu/~pikerc/das2C-tmp.tar.gz
   sha256: {{ sha256 }}
   
   
build:
   # This is the first build
   number: 1
   
requirements:
   build:
      - {{ compiler('c') }}
            
#   host:
#      - expat
#      - fftw
#      - zlib
#      - openssl
#      - pthreads4w [win]
      
#   run:
#      - expat
#      - fftw
#      - zlib
#      - openssl
#      - pthreads4w [win]
      
test:
   

about:
   home: https://github.com/das-developers/das2C
   license: LGPL-2.1
   license_file: LICENSE
   summary: das2 stream utilities and catalog client in C
