
# Go generate the sha-hash run
# HASH=$(openssl sha256  das2C-${VERSION}.tar.gz | awk '{print $2}')
#
# Example:
#  openssl sha256 das2C-tmp.tar.gz | awk '{print $2}'

{% set name = "das2c" %}
{% set conda_version = "2.3.0" %}
{% set git_version = "2.3.0" %}
#{% set sha256 = "6362189d746045b2294810f28d9319f60f1f035a3df71667a1d09677248f3e2e" %}
{% set sha256 = "6530b7b78e995f951ecf1598ca9dd9ff7ee7a8ba53ffcbc8d06d50ea0b4a0c4c" %}

package:
   name: {{ name }} 
   version: {{ conda_version }} 
   
source:
   fn:  das2C-{{ git_version }}.tar.gz
   #url: https://github.com/das-developers/das2C/archive/refs/tags/v{{ git_version }}.tar.gz
   url: https://space.physics.uiowa.edu/~pikerc/das2C-tmp.tar.gz
   sha256: {{ sha256 }}
   
   
build:
   # This is the zeroth build
   number: 0
   
requirements:
   build:
      - {{ compiler('c') }}
            
   host:
      - expat
      - fftw
      - zlib
      - openssl
      - pthreads4w [win]
      
   run:
      - expat
      - fftw
      - zlib
      - openssl
      - pthreads4w [win]
      
test:
   

about:
   home: https://github.com/das-developers/das2C
   license: LGPL-2.1
   license_file: LICENSE
   summary: das2 stream utilities and catalog client in C
